
// Keywords can be grouped using a string for the second array item

var sparql1Keywords = [ [ "BASE", "" ], [ "PREFIX", "" ],
        [ "SELECT", "" ], [ "ASK", "" ], [ "CONSTRUCT", "" ],
        [ "DESCRIBE", "" ], [ "DISTINCT", "MODIFIER" ], [ "REDUCED", "" ],
        [ "FROM", "" ], [ "NAMED", "" ], [ "WHERE", "" ], [ "GRAPH", "" ],
        [ "UNION", "" ], [ "FILTER", "" ], [ "OPTIONAL", "" ],
        [ "ORDER", "MODIFIER" ], [ "LIMIT", "MODIFIER" ],
        [ "OFFSET", "MODIFIER" ], [ "BY", "MODIFIER" ], [ "ASC", "" ],
        [ "DESC", "" ], [ "STR", "STRING" ], [ "LANG", "" ],
        [ "LANGMATCHES", "STRING" ], [ "DATATYPE", "" ], [ "BOUND", "" ],
        [ "SAMETERM", "" ], [ "ISIRI", "TERM" ], [ "ISURI", "TERM" ],
        [ "ISBLANK", "TERM" ], [ "ISLITERAL", "TERM" ], [ "REGEX", "STRING" ] ];

var sparql11Query = [ [ "BASE", "" ], [ "PREFIX", "" ], [ "SELECT", "" ],
        [ "ASK", "" ], [ "CONSTRUCT", "" ], [ "DESCRIBE", "" ],
        [ "DISTINCT", "MODIFIER" ], [ "REDUCED", "" ], [ "FROM", "" ],
        [ "NAMED", "" ], [ "WHERE", "" ], [ "GRAPH", "" ], [ "UNION", "" ],
        [ "FILTER", "" ], [ "OPTIONAL", "" ], [ "ORDER", "MODIFIER" ],
        [ "LIMIT", "MODIFIER" ], [ "OFFSET", "MODIFIER" ],
        [ "BY", "MODIFIER" ], [ "ASC", "" ], [ "DESC", "" ],
        [ "STR", "STRING" ], [ "LANG", "" ], [ "LANGMATCHES", "STRING" ],
        [ "DATATYPE", "" ], [ "BOUND", "" ], [ "SAMETERM", "" ],
        [ "ISIRI", "TERM" ], [ "ISURI", "TERM" ], [ "ISBLANK", "TERM" ],
        [ "ISLITERAL", "TERM" ], [ "REGEX", "STRING" ], [ "HAVING", "" ],
        [ "GROUP", "" ], [ "VALUES", "" ], [ "IF", "" ], [ "COALESCE", "" ],
        [ "EXISTS", "" ], [ "NOT", "" ], [ "ISNUMERIC", "TERM" ],
        [ "IRI", "TERM" ], [ "BNODE", "TERM" ], [ "STRDT", "TERM" ],
        [ "STRLANG", "TERM" ], [ "UUID", "TERM" ], [ "STRUUID", "TERM" ],
        [ "STRLEN", "STRING" ], [ "SUBSTR", "STRING" ], [ "LCASE", "STRING" ],
        [ "UCASE", "STRING" ], [ "STRSTARTS", "STRING" ],
        [ "STRENDS", "STRING" ], [ "CONTAINS", "STRING" ],
        [ "STRBEFORE", "STRING" ], [ "STRAFTER", "STRING" ],
        [ "ENCODE_FOR_URI", "STRING" ], [ "CONCAT", "STRING" ],
        [ "REPLACE", "STRING" ], [ "NOW", "DATE" ], [ "YEAR", "DATE" ],
        [ "MONTH", "DATE" ], [ "DAY", "DATE" ], [ "HOURS", "DATE" ],
        [ "MINUTES", "DATE" ], [ "SECONDS", "DATE" ], [ "TIMEZONE", "DATE" ],
        [ "TZ", "DATE" ], [ "MD5", "HASH" ], [ "SHA1", "HASH" ],
        [ "SHA256", "HASH" ], [ "SHA384", "HASH" ], [ "SHA512", "HASH" ],
        [ "ABS", "NUMERIC" ], [ "ROUND", "NUMERIC" ], [ "CEIL", "NUMERIC" ],
        [ "FLOOR", "NUMERIC" ], [ "RAND", "NUMERIC" ],
        [ "REDUCED", "MODIFIER" ], [ "COUNT", "AGGREGATE" ],
        [ "SUM", "AGGREGATE" ], [ "MIN", "AGGREGATE" ], [ "MAX", "AGGREGATE" ],
        [ "AVG", "AGGREGATE" ], [ "SAMPLE", "AGGREGATE" ],
        [ "GROUP_CONCAT", "AGGREGATE" ] ];

var sparql11Update = [ [ "BASE", "" ], [ "PREFIX", "" ], [ "SELECT", "" ],
        [ "DISTINCT", "MODIFIER" ], [ "REDUCED", "" ], [ "NAMED", "" ],
        [ "WHERE", "" ], [ "GRAPH", "" ], [ "TO", "UPDATE" ], [ "USING", "" ],
        [ "DEFAULT", "" ], [ "ALL", "" ], [ "UNION", "" ], [ "FILTER", "" ],
        [ "OPTIONAL", "" ], [ "ORDER", "MODIFIER" ], [ "LIMIT", "MODIFIER" ],
        [ "OFFSET", "MODIFIER" ], [ "BY", "MODIFIER" ], [ "ASC", "" ],
        [ "DESC", "" ], [ "STR", "STRING" ], [ "LANG", "" ],
        [ "LANGMATCHES", "STRING" ], [ "DATATYPE", "" ], [ "BOUND", "" ],
        [ "SAMETERM", "" ], [ "ISIRI", "TERM" ], [ "ISURI", "TERM" ],
        [ "ISBLANK", "TERM" ], [ "ISLITERAL", "TERM" ], [ "REGEX", "STRING" ],
        [ "HAVING", "" ], [ "GROUP", "" ], [ "VALUES", "" ], [ "IF", "" ],
        [ "COALESCE", "" ], [ "EXISTS", "" ], [ "NOT", "" ],
        [ "ISNUMERIC", "TERM" ], [ "IRI", "TERM" ], [ "BNODE", "TERM" ],
        [ "STRDT", "TERM" ], [ "STRLANG", "TERM" ], [ "UUID", "TERM" ],
        [ "STRUUID", "TERM" ], [ "STRLEN", "STRING" ], [ "SUBSTR", "STRING" ],
        [ "LCASE", "STRING" ], [ "UCASE", "STRING" ],
        [ "STRSTARTS", "STRING" ], [ "STRENDS", "STRING" ],
        [ "CONTAINS", "STRING" ], [ "STRBEFORE", "STRING" ],
        [ "STRAFTER", "STRING" ], [ "ENCODE_FOR_URI", "STRING" ],
        [ "CONCAT", "STRING" ], [ "REPLACE", "STRING" ], [ "NOW", "DATE" ],
        [ "YEAR", "DATE" ], [ "MONTH", "DATE" ], [ "DAY", "DATE" ],
        [ "HOURS", "DATE" ], [ "MINUTES", "DATE" ], [ "SECONDS", "DATE" ],
        [ "TIMEZONE", "DATE" ], [ "TZ", "DATE" ], [ "MD5", "HASH" ],
        [ "SHA1", "HASH" ], [ "SHA256", "HASH" ], [ "SHA384", "HASH" ],
        [ "SHA512", "HASH" ], [ "ABS", "NUMERIC" ], [ "ROUND", "NUMERIC" ],
        [ "CEIL", "NUMERIC" ], [ "FLOOR", "NUMERIC" ], [ "RAND", "NUMERIC" ],
        [ "REDUCED", "MODIFIER" ], [ "COUNT", "AGGREGATE" ],
        [ "SUM", "AGGREGATE" ], [ "MIN", "AGGREGATE" ], [ "MAX", "AGGREGATE" ],
        [ "AVG", "AGGREGATE" ], [ "SAMPLE", "AGGREGATE" ],
        [ "GROUP_CONCAT", "AGGREGATE" ], [ "DATA", "UPDATE" ],
        [ "INSERT", "UPDATE" ], [ "DELETE", "UPDATE" ], [ "CREATE", "UPDATE" ],
        [ "DROP", "UPDATE" ], [ "COPY", "UPDATE" ], [ "MOVE", "UPDATE" ],
        [ "ADD", "UPDATE" ], [ "LOAD", "UPDATE" ], [ "INTO", "UPDATE" ],
        [ "WITH", "UPDATE" ], [ "SILENT", "UPDATE" ] ];

module.exports = {
    sparql1Keywords: sparql1Keywords,
    sparql11Query: sparql11Query,
    sparql11Update: sparql11Update
}

